### ISSUE TITLE
Explicitly State Tags in CI Pipeline

### ISSUE THREAD

**Issue by DiCanio** [num-codex/codex-processes#16]
When pushing a tag then the CI pipeline is not triggered. We were under the assumption that this should work since it is a push, too.

To fix this we need to configure the pipeline so that any tag having a prefix of `v` on branch `main` will trigger the pipeline.

```
on:
  push:
    branches:
    - main
    tags:
    - v**
```

This should do the trick.
